#!/bin/bash

PAGE_VERSION=$(grep 'Generated by Ork HERO Templates' page.html | cut -d ' ' -f6)
echo "page version: ${PAGE_VERSION}"
echo

GIT_TAG_VERSION=$(git tag | sort -Vr | head -1)
echo "git tag version: ${GIT_TAG_VERSION}"
echo

CHANGELOG_VERSION=$(grep '^## \[' CHANGELOG.md | head -1 | cut -d ']' -f1 | cut -d '[' -f2)
echo "changelog version: ${CHANGELOG_VERSION}"
echo

echo "dist template version:"
for FILE in dist/*.hde
do
    echo -n "  ${FILE}: "
    grep 'Generated by Ork HERO Templates' "${FILE}" | cut -d ' ' -f6
done
echo

echo "example template version:"
for FILE in examples/*.html
do
    echo -n "  ${FILE}: "
    grep 'Generated by Ork HERO Templates' "${FILE}" | cut -d ' ' -f6
done
echo
